version: '3'
services:

  #PHP Service
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    image: ${COMPOSE_PROJECT_NAME}-php:7.4.6-fpm
    command: sh -c "chown user -R /var/www && chmod 775 -R /var/www && php-fpm"
    # Remember to open conf/apache/docker.conf to change ProxyPassMatch to this container_name
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./conf/php:/usr/local/etc/php/conf.d
      - ./conf/php-fpm.d:/usr/local/etc/php-fpm.d
    networks:
      - app-network

  #Apache Service
  apache:
    image: httpd:latest
    container_name: ${COMPOSE_PROJECT_NAME}-apache
    command: sh -c "groupadd -g 1000 user && useradd -u 1000 -ms /bin/bash -g user user && httpd-foreground"
    restart: unless-stopped
    tty: true
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./src:/var/www
      - ./logs:/usr/local/apache2/logs
      - ./conf/apache:/usr/local/apache2/conf
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:8.0.19
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql/
    networks:
      - app-network

  #phpMyAdmin
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: unless-stopped
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    external_links:
      - mysql:db

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  mysql-data:
    driver: local
